# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageActionLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('data', models.TextField(blank=True)),
                ('time', models.DateTimeField()),
                ('created', models.BooleanField(default=False)),
                ('content_changed', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('unpublished', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_log_entries', to='wagtailcore.Page')),
                ('revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.PageRevision')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
