# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-25 14:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190206_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvocateSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('company_name', models.CharField(max_length=50)),
                ('company_location', models.CharField(max_length=50)),
                ('sector', models.CharField(choices=[('0', 'Advanced Manufacturing'), ('1', 'Aerospace'), ('2', 'Agri-Tech'), ('3', 'Aid Funded Business'), ('4', 'Airports'), ('5', 'Automotive'), ('6', 'Biotechnology and Pharmaceuticals'), ('7', 'Business (and Consumer) Services'), ('8', 'Capital Investment'), ('9', 'Clothing, Footwear and Fashion'), ('10', 'Communications'), ('12', 'Construction'), ('13', 'Creative and Media'), ('14', 'Defence (DSO)'), ('15', 'Education and Training'), ('16', 'Electronics and IT Hardware'), ('17', 'Energy'), ('18', 'Environment'), ('19', 'Financial Services (including Professional Services)'), ('20', 'Food and Drink'), ('21', 'Giftware, Jewellery and Tableware'), ('22', 'Global Sports'), ('23', 'Healthcare and Medical'), ('24', 'Household Goods, Furniture and Furnishings'), ('25', 'Infrastructure (Investment Only)'), ('26', 'Leisure and Tourism'), ('27', 'Life Sciences'), ('28', 'Marine'), ('29', 'Manufacturing'), ('30', 'Mass Transport'), ('31', 'Mining'), ('32', 'Nuclear'), ('33', 'Oil and Gas'), ('34', 'Ports and Logistics'), ('35', 'Power'), ('36', 'Railways'), ('37', 'Renewables'), ('38', 'Retail'), ('39', 'Security'), ('40', 'Software and Computer Services'), ('41', 'Space'), ('42', 'Technology'), ('43', 'Textiles, Interior Textiles and Carpets'), ('44', 'Other (please specify):')], max_length=255)),
                ('company_website', models.CharField(max_length=255)),
                ('employees_number', models.CharField(choices=[('0', 'Less than 10'), ('1', '10-50'), ('2', '50+')], max_length=255)),
                ('currently_export', models.BooleanField()),
                ('advertising_feedback', models.CharField(choices=[('0', 'In the press'), ('1', 'International Trade Advisor'), ('2', 'Anothercompany'), ('3', 'Tradeassociation'), ('4', 'On great.gov.uk'), ('5', 'Email from DIT'), ('6', 'At an event'), ('7', 'Other (please specify):')], max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Advocate SignUp Form',
                'verbose_name_plural': 'Advocate SignUp Forms',
            },
        ),
    ]
