# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190206_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadcrumb',
            name='label_ar',
        ),
        migrations.RemoveField(
            model_name='breadcrumb',
            name='label_de',
        ),
        migrations.RemoveField(
            model_name='breadcrumb',
            name='label_en_gb',
        ),
        migrations.RemoveField(
            model_name='breadcrumb',
            name='label_es',
        ),
        migrations.RemoveField(
            model_name='breadcrumb',
            name='label_fr',
        ),
        migrations.RemoveField(
            model_name='breadcrumb',
            name='label_ja',
        ),
        migrations.RemoveField(
            model_name='breadcrumb',
            name='label_pt',
        ),
        migrations.RemoveField(
            model_name='breadcrumb',
            name='label_pt_br',
        ),
        migrations.RemoveField(
            model_name='breadcrumb',
            name='label_ru',
        ),
        migrations.RemoveField(
            model_name='breadcrumb',
            name='label_zh_hans',
        ),
    ]
