# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-25 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_exportcontact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExportContact',
            new_name='AdvocateSignUp',
        ),
    ]
