# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail_i18n.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_i18n', '0005_language_is_active'),
        ('wagtailcore', '0040_page_draft_title'),
        ('great_international', '0005_auto_20190320_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalLocaleRootPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='root_pages', to='wagtail_i18n.Language')),
                ('locale', models.ForeignKey(default=wagtail_i18n.models.Locale.default_id, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='InternationalRegionRootPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='root_page', to='wagtail_i18n.Region')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterUniqueTogether(
            name='internationallocalerootpage',
            unique_together=set([('translation_key', 'locale')]),
        ),
    ]
