# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_i18n', '0005_language_is_active'),
        ('great_international', '0008_enable_wagtail_i18n_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalarticlelistingpage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='internationalarticlelistingpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='internationalarticlepage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='internationalarticlepage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='internationalcampaignpage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='internationalcampaignpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='internationalcuratedtopiclandingpage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='internationalcuratedtopiclandingpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='internationalguidelandingpage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='internationalguidelandingpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='internationalsectorpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='internationaltopiclandingpage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='internationaltopiclandingpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='internationalarticlelistingpage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='internationalarticlepage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='internationalcampaignpage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='internationalcuratedtopiclandingpage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='internationalguidelandingpage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='internationalsectorpage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='internationaltopiclandingpage',
            unique_together=set([('translation_key', 'locale')]),
        ),
    ]
