# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_i18n', '0010_language_and_locale_ordering'),
        ('invest', '0021_wagtail_i18n_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highpotentialopportunitydetailpage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='highpotentialopportunitydetailpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='highpotentialopportunityformpage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='highpotentialopportunityformpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='highpotentialopportunityformsuccesspage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='highpotentialopportunityformsuccesspage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='investhomepage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='regionlandingpage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='regionlandingpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='sectorlandingpage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='sectorlandingpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='sectorpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='setupguidelandingpage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='setupguidelandingpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='setupguidepage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='setupguidepage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='highpotentialopportunitydetailpage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='highpotentialopportunityformpage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='highpotentialopportunityformsuccesspage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='infopage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='investhomepage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='regionlandingpage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='sectorlandingpage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='sectorpage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='setupguidelandingpage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='setupguidepage',
            unique_together=set([('translation_key', 'locale')]),
        ),
    ]
