# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_i18n', '0011_model_managers'),
        ('wagtailcore', '0040_page_draft_title'),
        ('invest', '0022_wagtail_i18n_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestLocaleRootPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('service_name', models.CharField(choices=[('FIND_A_SUPPLIER', 'Find a Supplier'), ('EXPORT_READINESS', 'Export Readiness'), ('INVEST', 'Invest'), ('COMPONENTS', 'Components'), ('GREAT_INTERNATIONAL', 'Great International')], db_index=True, max_length=100, null=True)),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='investlocalerootpage',
            unique_together=set([('translation_key', 'locale')]),
        ),
    ]
