# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 17:04
from __future__ import unicode_literals

from django.db import migrations

from wagtail_i18n.bootstrap import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('find_a_supplier', '0070_wagtail_i18n_1'),
    ]

    operations = [
        BootstrapTranslatableModel('find_a_supplier.IndustryArticlePage'),
        BootstrapTranslatableModel('find_a_supplier.IndustryContactPage'),
        BootstrapTranslatableModel('find_a_supplier.IndustryLandingPage'),
        BootstrapTranslatableModel('find_a_supplier.IndustryPage'),
        BootstrapTranslatableModel('find_a_supplier.IndustryPageArticleSummary'),
        BootstrapTranslatableModel('find_a_supplier.LandingPage'),
        BootstrapTranslatableModel('find_a_supplier.LandingPageArticleSummary'),
    ]
