# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_i18n', '0010_language_and_locale_ordering'),
        ('find_a_supplier', '0071_wagtail_i18n_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryarticlepage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='industryarticlepage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='industrycontactpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='industrylandingpage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='industrylandingpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='industrypage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='industrypagearticlesummary',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='industrypagearticlesummary',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='landingpagearticlesummary',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtail_i18n.Locale'),
        ),
        migrations.AlterField(
            model_name='landingpagearticlesummary',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='industryarticlepage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='industrycontactpage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='industrylandingpage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='industrypage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='industrypagearticlesummary',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='landingpage',
            unique_together=set([('translation_key', 'locale')]),
        ),
        migrations.AlterUniqueTogether(
            name='landingpagearticlesummary',
            unique_together=set([('translation_key', 'locale')]),
        ),
    ]
